### ISSUE TITLE
“WebDriverException: Message: chrome not reachable” on circleci

### ISSUE THREAD

**Issue by pronitagrawalvera** [SFDO-Tooling/CumulusCI#1440]
I am getting "WebDriverException: Message: chrome not reachable" error when I am running my test on circleci

I am using below approach on my local machine,it is working fine but getting on circleci
```
Setup chromedriver
    Log    ${CURDIR}
    Append To Environment Variable    PATH    ${CURDIR}
```
![chromedriver exception](https://user-images.githubusercontent.com/58841386/71897334-4d408080-317c-11ea-82ab-13d692fee960.PNG)

circleci yml file
```

version: 2  orbs:   
win: circleci/windows@1.0.0 jobs: # A basic unit of work in a run   
build: # runs not using Workflows must have a `build` job as entry point 
        # directory where steps are run
        working_directory: ~/repo
        docker: # run the steps with Docker
          # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
          - image: circleci/python:3.7.2
            environment: # environment variables for primary container
              CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain   steps: # steps that comprise the `build` job
          - checkout 
     - run:
                 name: Install Python deps in a venv
                 command: |
                     virtualenv venv                 
                     venv/bin/pip install -r requirements_dev.txt
    - run:
              name: Download sfdx
              command: |
                mkdir sfdx
                sudo wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz | tar xJ -C sfdx --strip-components 1
          - run:
              name: Install sfdx
              command: |
                ./sfdx/install
                sfdx
                mkdir tmp   
     - run: 
                 name: Create Hub
                 command: |
                     openssl enc -nosalt -aes-256-cbc -d -in access/server.key.enc -out access/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
                     sfdx force:auth:jwt:grant -i $HUB_CONSUMER_KEY -f ./access/server.key -u $HUB_SFDX_USER --setdefaultdevhubusername -a hub
          - run:
                 name: Create Org
                 command: |
                     venv/bin/cci flow run qa_org --org dev    
                     venv/bin/cci task run robot --org dev -o suites robot/tests/Activities.robot -o include test -o vars LocalOrRemote:Local,Browser:googlechrome
```
