### ISSUE TITLE
Scratch org created without namespace even if namespaced is True

### ISSUE THREAD

**Issue by MelaHub** [SFDO-Tooling/CumulusCI#1674]
Hi there,
I'm using the following cumulusci.yml file

```
project:
    name: project-name
    package:
        name:  ProjectName
        namespace: project-name
        api_version: '48.0'
    source_format: sfdx

orgs:
    scratch:
        scratch-name:
            config_file: orgs/dev.json
            days: 3
            namespaced: True

```

From the docs it looks like this should be enough to create a scratchorg with a namespace. However, by running:
`cci org info scratch-name`

The command that is actually executed is 
`sfdx force:org:create -f orgs/dev.json -n --durationdays 3 -a "project-name__scratch-name" `

it looks like the -n (no namespace) is there even if it shouldn't. Am I missing something?
