### ISSUE TITLE
How to give specify org name in cumulusCI yml against custom task?

### ISSUE THREAD

**Issue by sfdcale** [SFDO-Tooling/CumulusCI#1681]
```
flows:
    LoadData:
        steps:
            1:
                task: ExtractData
            2:
                task: LoadData

tasks:        
    ExtractData:
        description: Extracts data from UAT Sandbox
        class_path: cumulusci.tasks.bulkdata.ExtractData
        options:
            mapping: datasets/mapping.yml
            sql_path: datasets/data.sql

    LoadData:
        description: Loads data into default org(dev sandbox)
        class_path: cumulusci.tasks.bulkdata.LoadData
        options:
            mapping: datasets/mapping.yml
            sql_path: datasets/data.sql
```

I would like to run the command `cci flow run load` so that this extracts data from UAT sandbox and loads data into dev sandbox(default org). How can I achieve this?

Right now, I am running the below two commands manually one after other and would like to combine this into one flow.
`cci task run extract_dataset -o mapping datasets/mapping.yml -o sql_path datasets/data.sql --org uat`
`cci task run load_dataset -o mapping datasets/mapping.yml -o sql_path datasets/data.sql`
