### ISSUE TITLE
Tasks/Flow ordering with decimal numbering after a whole number throws an error

### ISSUE THREAD

**Issue by davidjray** [SFDO-Tooling/CumulusCI#1914]
**Error:** `TypeError: '<' not supported between instances of 'int' and 'str'`
**Relevant info from gist:**
```
File "/usr/local/Cellar/python@3.8/3.8.3_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
```

**Desc**
Trying to add tasks numbering using decimals (1, 1.1, 1.2...) throws the listed error. It seems to be related when calling flows from a dependency.

I am using 
```
sources:
    k12kit:
        github: https://github.com/SalesforceFoundation/k12-architecture-kit
```

**Repro Steps**
1. Create a flow that calls tasks/flows from a source repo
2. Number the flow starting with 1 (a whole number)
3. Make the next step 1.1
```
    # This will fail
    test:
        description: Test
        steps:
            1:
                flow: k12kit:dependencies
            1.1:
                task: k12kit:install_managed
```
4. Run the flow, see error
5. Change the 1 step to 1.0
```
    # This will RUN
    test:
        description: Test
        steps:
            1.0:
                flow: k12kit:dependencies
            1.1:
                task: k12kit:install_managed
```
6. Run the flow, no error

**Context**
- CumulusCI version - 3.15.0 brew install
- Python version - 3.8.3
- OS: maxOS 10.14.6

**Gist**
https://gist.github.com/davidjray/64d4fa89be17eb5e797b03381aa90f6c

**Additional information**
Adding tasks as
