### ISSUE TITLE
github repository dependency - cannot default metadata folder

### ISSUE THREAD

**Issue by Cardu** [SFDO-Tooling/CumulusCI#2388]
I'm interested in functionality that solves a current problem, I'd like to use another repo as a dependency, but the metadata in the target repo is under "force-app" folder

**Describe the solution you'd like**
I'd like an option to change the default metadata folder name, like:

```
roject:
    dependencies:
        - github: https://github.com/...
          metadata_folder: force-app
 ```

**Additional context**
While testing on my machine, it seems that changing folder name [here](https://github.com/SFDO-Tooling/CumulusCI/blob/4662b3ae423a0ad3d809c9346d0ca1edbbcf0265/cumulusci/core/config/project_config.py#L765) and [here](https://github.com/SFDO-Tooling/CumulusCI/blob/4662b3ae423a0ad3d809c9346d0ca1edbbcf0265/cumulusci/core/config/project_config.py#L767) was enough to get the desired behaviour
