### ISSUE TITLE
Missing documentation for sources: release:

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/CumulusCI#2439]
I see this syntax in a project:

```
sources:
    other_proj:
        github: https://github.com/SalesforceFoundation/other-project
        release: latest_beta
```

But I don't see the word "release:" in this document:

https://cumulusci.readthedocs.io/en/latest/config.html#tasks-and-flows-from-a-different-project
