### ISSUE TITLE
cumulusci.yml doesn't recognize changes

### ISSUE THREAD

**Issue by Gedoval** [SFDO-Tooling/CumulusCI#3019]
### Describe the bug

Hi,

I have a cumulusci.yml on the root of my project and only there. No .yml file on %homepath%\.cumulusci\project_name\ or %homepath%\.cumulusci\ (I'm on Windows 10).
I made some changes to the path to the scratch org definition file. This is the old configuration:
```
orgs:
    scratch:
        service_cloud:
            config_file: camel-middleware/serviceCloudQA/QAEnv/config/project-scratch-def.json
            days: 15
            namespaced: false
```

And this is the new one:
```
orgs:
    scratch:
        service_cloud:
            config_file: camel-middleware/ServiceCloud/config/project-scratch-def.json
            days: 15
            namespaced: false
```

But when I run **cci org info service_cloud** I get this error on the log file:

>   File "C:\Users\Usuario\.local\pipx\venvs\cumulusci\lib\site-packages\cumulusci\core\config\ScratchOrgConfig.py", line 116, in _build_org_create_args
    with open(self.config_file, "r") as org_def:
FileNotFoundError: [Errno 2] No such file or directory: 'camel-middleware/serviceCloudQA/QAEnv/config/project-scratch-def.json'

So, do I need to refresh something to make Cumulus acknowledge these changes ? I tried commiting the change on the repo, executing the command from a new cmd, but I kept getting the same error. I couldn't find anything on the docs relating to this issue.

Thanks in advance.

### Reproduction steps

1. Create a new scratch org definition on cumulusci.yml
2. Run the command **cci org info <scratch_name>** and a new scratch org will be created
3. Change the path to the scratch definition file on cumulusci.yml
4. Run the command **cci org info <scratch_name>** and a error should be displayed.

### Your CumulusCI and Python versions

```
CumulusCI version: 3.49.0 (C:\Users\Usuario\.local\bin\cci)
Python version: 3.9.2 (C:\Users\Usuario\.local\pipx\venvs\cumulusci\Scripts\python.exe)
```

### Operating System

Windows 10

### Windows environment

Command Prompt, PowerShell
