### ISSUE TITLE
Setup SFDX_AUTH_URL on github without installing locally cci

### ISSUE THREAD

**Issue by VinceFINET** [SFDO-Tooling/CumulusCI#3063]
### Describe the bug

Hello

I would like to make cumulusci work for my project.
I followed the steps described at https://cumulusci.readthedocs.io/en/latest/github_actions.html

When running the default Apex Test action (my project does not have Apex class but i need to start from something), The action gets this error:
![image](https://user-images.githubusercontent.com/3799275/152514501-c0e37726-bf92-4021-a45e-e636838462b7.png)

My secrets (without the values!) look like this:
![image](https://user-images.githubusercontent.com/3799275/152514859-4c35c108-7bef-473b-a091-cfff509882b8.png)

I tried to use a JWT token instead but no luck either.

### Reproduction steps

Just following the steps at https://cumulusci.readthedocs.io/en/latest/github_actions.html
without having CCI installed locally

### Your CumulusCI and Python versions

I don't want to have CCI and Python installed on my machine.

### Operating System

MacOS

**Comment by davisagli** [comment]
@VinceFINET At first glance this doesn't look like an issue with CumulusCI. It looks like you have not set up SFDX_AUTH_URL in the format expected by sfdx.

**Comment by VinceFINET** [comment]
When I take a closer look a te output I think the error is link to that line:
```
Run echo  > sfdx_auth
  echo  > sfdx_auth
  sfdx force:auth:sfdxurl:store -f sfdx_auth -d
```

The file `sfdx_auth` should include the variable `SFDX_AUTH_URL`
But as you can see, the value is empty so the `sfdx_auth`is also an empty file.

I am wondering since GitHub added a layer in the secret settings (aka "environment") it is possible that CumulusCI yaml script is not getting correctly the value ???

and then the documentation might be out of date ??

**Comment by VinceFINET** [comment]
in the documentation, the apex test yml example file contains a reference to the secret:
```
name: Apex Tests

on: [push]

env:
  CUMULUSCI_SERVICE_github: **${{ secrets.CUMULUSCI_SERVICE_github }}**

jobs:
  unit_tests:
    name: "Run Apex tests"
```

I think the environment need to be specify....

**Comment by davisagli** [comment]
Github Actions sanitizes its output to make sure secrets are not shown, so I would not assume that the fact that SFDX_AUTH_URL is not shown means it was not actually stored in the sfdx_auth file.

> Instead of ${{ secrets.SFDX_AUTH_URL }} maybe ${{ secrets.cumulusci.SFDX_AUTH_URL }} (because in my case the environment is called cumulusci

This may indeed be the case; when the docs were written GitHub did not have this feature of multiple Environments, and I am not yet familiar with the correct way to reference variables from an Environment in Github Actions. I'd suggest consulting the documentation for Github Actions.

**Comment by VinceFINET** [comment]
Ok got it!

It was indeed not getting the value.

When it's working you see this in the log:
```
Run echo *** > sfdx_auth
  echo *** > sfdx_auth
  sfdx force:auth:sfdxurl:store -f sfdx_auth -d
```

Anyway I got it work by adding the `environment` parameter just like in the following example:
```
name: Apex Tests

on: [push]

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}

jobs:
  unit_tests:
    name: "Run Apex tests"
    runs-on: ubuntu-latest
    environment: cumulusci
    steps:
```

Source of the GitHub documentation:
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-secrets

Environment seems mandatory now to have secrets in github.
