### ISSUE TITLE
create_package_version does not appear to be incrementing the minor version for a 2GP beta release

### ISSUE THREAD

**Issue by ryanfollmer** [SFDO-Tooling/CumulusCI#3107]
### Describe the bug

I'm hoping this is just an issue where I misconfigured something. But here goes...

In our github action, we are running the following command:
```
cci flow run release_2gp_beta --org feature_namespaced --delete-org
```

In cumulus.yml, we have set a few options on the release_2gp_beta flow (although we shouldn't have to set version_type = minor because thats the default):
```
    release_2gp_beta:
        steps:
            1:
                task: create_package_version
                options:
                    post_install_script: PostInstallHandler
                    version_type: minor
            4:
                task: None
```
Expected Result: The minor number of the version number should be incremented
Actual Result: Only the build number is getting incremented in the version number
 - Executed release_2gp_beta 3 times and I now have 3 beta packages with version numbers:
 -- 0.1.0.1
 -- 0.1.0.2
 -- 0.1.0.3 

I also have those 3 packages as release tags in my github repo
 - beta/0.1.0.3
 - beta/0.1.0.2
 - beta/0.1.0.1

When I query the Package2Version object using the following:
```
SELECT Package2Id, SubscriberPackageVersionId, MajorVersion, MinorVersion, PatchVersion, BuildNumber, ReleaseVersion, IsReleased 
FROM Package2Version 
WHERE Package2Id='0Ho2I000000GmcASAS' 
ORDER BY MajorVersion DESC, MinorVersion DESC, PatchVersion DESC, BuildNumber DESC 
LIMIT 10
```
I receive the following results:
|Package2Id        |SubscriberPackageVersionId|MajorVersion|MinorVersion|PatchVersion|BuildNumber|IsReleased|
|------------------|--------------------------|------------|------------|------------|-----------|----------|
|0Ho2I000000GmcASAS|04t2I000000WoOdQAK        |0           |1           |0           |3          |false     |
|0Ho2I000000GmcASAS|04t2I000000WoOTQA0        |0           |1           |0           |2          |false     |
|0Ho2I000000GmcASAS|04t2I000000WoKWQA0        |0           |1           |0           |1          |false     |

### Reproduction steps

1. Create a sample 2GP salesforce project
2. Run the following command at least twice to observe the version number output: cci flow run release_2gp_beta --org <yourorg>

 

### Your CumulusCI and Python versions

cumulus version: 3.53
python: 3.9.10

### Operating System

Github action: ubuntu-latest

### CumulusCI installation method

pip

**Comment by davisagli** [comment]
What releases exist for this repository in GitHub? The built-in definition of the `release_2gp_beta` flow sets the `version_base` option of the `create_package_version` task to `latest_github_release`, which means that the task will look for the latest release in github, and increment from its version number.

If you'd like to instead increment from the most recent version in the Dev Hub, you can set `version_base: null` in the task options.

**Comment by ryanfollmer** [comment]
I do not have any releases in github. I have only packaged 3 beta versions and those are defined as release tags in github... but they are prefixed with beta as described in the issue above.

Screenshot for reference if that helps:
![image](https://user-images.githubusercontent.com/2651539/156800613-b7ed55c5-87bc-432a-a5f3-af1a6d757cdc.png)

**Comment by ryanfollmer** [comment]
In cumulus.yml, passing in version_base: null is not working. I changed it to the following:
```
    release_2gp_beta:
        steps:
            1:
                task: create_package_version
                options:
                    post_install_script: PostInstallHandler
                    version_base: null
            4:
                task: None
```

But then in my build log, I see this:
```
                    ------------------------------------------------------------
                    Running task: create_package_version                        
                    ------------------------------------------------------------
                                                                                
                    Options:                                                    
                      package_name: RNP App              
                      package_type: Managed                                     
                      version_base: latest_github_release                       
                      version_type: minor                                       
                      skip_validation: False                                    
                      post_install_script: PostInstallHandler                   
                      force_upload: True                                        
                      ancestor_id: latest_github_release                        
                      create_unlocked_dependency_packages: False   
```

I also tried passing "null", but the process errored out saying it couldn't parse that yml value: "Error: Could not parse version number: null"
