### ISSUE TITLE
Ability to Define Flow Options in cumulusci.yml

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3162]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Does your feature request solve a current problem?

Currently, a flow option can only be executed when running the flow as a command. It would be helpful to be able to define flow options in the cumulusci.yml file.

### Describe the solution you'd like

Currently when you run a command like `cci flow run dev_org -o robot__vars AUTH_PROVIDER_SECRET:MY_SECRET`, the `robot__vars` option can only be defined in the command. It would be nice to be able to do it in the cumulusci.yml similar to this:

```
    dev_org:
        description: Automates dev org setup.
        options:
            robot__vars:AUTH_PROVIDER_SECRET:MY_SECRET
        steps:
            1:
                task: robot
                options:
                    suites: utils/create_authprovider/create_authprovider.robot
```

So that you could simply run `cci flow run dev_org` and still get options for that flow respected.

I would expect this to work for any sub-flows that have options defined as well when running the parent flow.
