### ISSUE TITLE
CumulucCI Metadeploy connect utf-8 invalid start byte

### ISSUE THREAD

**Issue by ChrisHobackExp** [SFDO-Tooling/CumulusCI#3163]
### Describe the bug

Attempting to connect to Metadeploy and display the recent connection information. Displaying the connection info returns `Error: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte`

We are using ubuntu-latest in the Github Workflow yaml. Installation of sfdx and cumulus are per the example in the Cumulus Documentation located at https://cumulusci.readthedocs.io/en/latest/github_actions.html.

Our goal is to create a Github Metadeploy manual workflow action that allows the users to send the CumulusCI information to a metadeploy site hosted on Heroku.

NOTE:
1 - I've confirmed that the cumulusci.yml file for our project is utf-8. However I'm thinking this shouldn't even matter given the cumulusci commands causing the issue shouldn't reference the yml file.
2 - One thing I've noticed is that even if the metadeploy connection parameters for `cci service connect metadeploy --url <METADEPLOY_SITE_URL> --token <METADEPLOY_TOKEN>` are incorrect, the system still returns like the service connection was successful.
3 - The Metadeploy site we are using appears to be running correctly, as I am able to run the connection and metadeploy publish commands locally on my windows machine without issue.

### Reproduction steps

1. Create a Github workflow using the following workflow yaml:
```
name: Metadeploy Push

on: 
  workflow_dispatch:
    inputs:
      metadeploy_annotation_tag:
        description: 'The custom annotation tag that will be sent to Metadeploy'     
        required: true
        default: 'beta/0.0'

env:
  CUMULUSCI_SERVICE_github: ${{ secrets.CUMULUSCI_SERVICE_github }}

jobs:
  metadeploy_job:
    name: "Send to MetaDeploy"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo "metadeploy_annotation_tag: ${{ github.event.inputs.metadeploy_annotation_tag }}"
    - run: |
        echo "METADEPLOY_TOKEN: ${{ secrets.METADEPLOY_TOKEN }}"
    - name: Install Salesforce CLI
      run: |
        mkdir sfdx
        wget -qO- https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz | tar xJ -C sfdx --strip-components 1
        echo $(realpath sfdx/bin) >> $GITHUB_PATH
    - name: Authenticate Dev Hub
      run: |
        echo ${{ secrets.SFDX_AUTH_URL }} > sfdx_auth
        sfdx force:auth:sfdxurl:store -f sfdx_auth -d
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - name: Install CumulusCI
      run: |
        python -m pip install -U pip
        pip install cumulusci
    - run: |
        pip install --upgrade cumulusci
    - run: |
        cci service connect metadeploy --url <METADEPLOY_SITE_URL> --token <METADEPLOY_TOKEN>
    - run: |
        cci service info metadeploy
```
2. Manually kick off the workflow job. Note that the metadeploy_annotation_tag parameter isn't hooked in
3. Wait for the workflow to fail when attempting to display a connection to metadeploy. This same error displays on the metadeploy publish command as well.

### Your CumulusCI and Python versions

CumulusCI version: 3.56.0 (/opt/hostedtoolcache/Python/3.[8](https://github.com/XXX/runs/6066657821?check_suite_focus=true#step:10:8).12/x64/bin/cci)
Python version: 3.8.12 (/opt/hostedtoolcache/Python/3.8.12/x64/bin/python)

### Operating System

ubuntu-latest (via Github Workflow)

### CumulusCI installation method

pip

### Github  Workflow Error

```
Run cci service connect metadeploy --url XXX --token ***
  cci service connect metadeploy --url XXX --token ***
  shell: /usr/bin/bash -e {0}
  env:
    CUMULUSCI_SERVICE_github: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.9.1[2](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:11:2)/x64
[04/18/22 18:4[3](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:11:3):29] Unable to store an encryption key. Any orgs or services     
                    written to disk will not be encrypted.                      
No service name specified. Using 'default' as the service name.
Service metadeploy:default is now connected
0s
Run cci service info metadeploy
  cci service info metadeploy
  shell: /usr/bin/bash -e {0}
  env:
    CUMULUSCI_SERVICE_github: ***
    pythonLocation: /opt/hostedtoolcache/Python/3.9.12/x6[4](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:11:4)
[04/1[8](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:11:8)/22 [1](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:12:1)8:4[3](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:12:3):30] Unable to store an encryption key. Any orgs or services     
                    written to disk will not be encrypted.                      
Error: 'utf-[8](https://github.com/XXX/runs/6066759528?check_suite_focus=true#step:12:8)' codec can't decode byte 0x80 in position 0: invalid start byte
Run this command for more information about debugging errors: cci error --help
Error: Process completed with exit code 1.
```
