### ISSUE TITLE
Update Admin Profile task fails when specifying records types without custom package.xml

### ISSUE THREAD

**Issue by dcinzona** [SFDO-Tooling/CumulusCI#3165]
### Describe the bug

When running the task `update_admin_profile` and specifying a record type that is not present in the default package.xml, and without specifying a custom package.xml, an error is returned stating:
```cumulusci.core.exceptions.TaskOptionsError: Record Type {record_type} not found in retrieved {profile_api_name}.profile```

### Reproduction steps

1. Create a new record type for Case, called "Case" in your org
2. Create a task in `cumulusci.yml`
```yaml
    update_admin_profile:
        options:
            api_names:
                - Admin
            record_types:
                - record_type: "Case.Case"
                  default: true
```
3. Run `cci task run update_admin_profile --org <alias>`

### Your CumulusCI and Python versions

CumulusCI version: 3.56.0 (/Users/gtandeciarz/.pyenv/versions/cci/bin/cci)
Python version: 3.10.4 (/Users/gtandeciarz/.pyenv/versions/cci/bin/python)

### Operating System

Mac OS 12.3.1

### CumulusCI installation method

pip
