### ISSUE TITLE
Metadata transforms not working

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/CumulusCI#3477]
### Describe the bug

I'm trying to replace email addresses in email templates by the current user's email address.

Here are some test transforms : 
```
  deploy_pre:
    options:
      transforms:
        - transform: find_replace
          options:
            patterns:
              - find: firstname1.lastname1@test.com
                inject_username: True
              - find: firstname2.lastname2@test.com
                replace: test-xyz@example.com
```

I'm getting this error : 
```
% cci task run deploy_pre --org beta        

Error: The transform spec is not valid. See CumulusCI documentation for details of how to specify transforms. The validation error was 2 validation errors for SourceTransformList
__root__ -> 0 -> __root__ -> patterns -> 0 -> replace
  field required (type=value_error.missing)
__root__ -> 0 -> __root__ -> patterns -> 0 -> replace_env
  field required (type=value_error.missing)
Run this command for more information about debugging errors: cci error --help
```

### Reproduction steps

1. create a file `unpackaged/pre/email/test.emailFolder-meta.xml` with the following contents : 
```
<EmailTemplateFolder xmlns="http://soap.sforce.com/2006/04/metadata">
    <folderShares>
        <accessLevel>EditAllContents</accessLevel>
        <sharedTo>firstname1.lastname1@test.com</sharedTo>
        <sharedToType>User</sharedToType>
    </folderShares>
    <folderShares>
        <accessLevel>EditAllContents</accessLevel>
        <sharedTo>firstname2.lastname2@test.com</sharedTo>
        <sharedToType>User</sharedToType>
    </folderShares>
</EmailTemplateFolder>
```
2. add this to your cumulusci.yml : 
```
  deploy_pre:
    options:
      transforms:
        - transform: find_replace
          options:
            patterns:
              - find: firstname1.lastname1@test.com
                inject_username: True
              - find: firstname2.lastname2@test.com
                replace: test-xyz@example.com
```
3. run `cci task run deploy`

### Your CumulusCI and Python versions

% cci version
CumulusCI version: 3.70.0 (/Users/rupert/.local/bin/cci)
Python version: 3.10.2 (/Users/rupert/.local/pipx/venvs/cumulusci/bin/python)

### Operating System

MacOS 11.7.2

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/RupertBarrow/1434c5dbd443e57bab364941a9e4a10a

### Additional information

As a sidenote : 
To work around this problem, I tried using the "dx" task to run the `force:source:deploy`command, hoping it would make replacements which I had defined in my sfdx-project.json file. This did not work.
I suggest that in the CCI docs, in the chapter about metadata transforms, you point out that CCI runs SFDX deploy tasks which do *not* make metadata replacements.
