### ISSUE TITLE
Error when running `github_package_data` with "Build Feature Test Package" after running `build_feature_test_package`

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3484]
### Describe the bug

I'm attempting to set up a flow that allows me to build 2GP packages for testing on feature branches based on this documentation. When can build 2GP packages just find using `build_feature_test_package` but always get an error when running `ci_feature_2gp` on the task `github_package_data`.

### Reproduction steps

1. In a CCI project fully setup so that it will not error when running `build_feature_test_package `, run `cci flow run build_feature_test_package`
2. Run `cci task run github_package_data --context "Build Feature Test Package"`

Result:
- Error: `Error: Could not find package version id in 'Build Feature Test Package' commit status for commit 
92e4c106fa29716eb59067c73cc0982deb3e56f0.`
- Gist: https://gist.github.com/Julian88Tex/85d9fd6869b9a419165914d2d903c9d4

Expected Result:
- Not entirely sure since I haven't seen it successfully run but I suspect it would provide me with a package version ID located in the commit's commit status.set up

### Your CumulusCI and Python versions

- Gist of `build_feature_test_package` command run which has no errors: https://gist.github.com/Julian88Tex/eeacf2c43cc6494d6278572ed811a591
- Attempting to go through these steps but finding it challenging without more examples: https://cumulusci.readthedocs.io/en/latest/2gp-testing.html#building-2gp-beta-packages-in-continuous-integration

### Operating System

macOS 13.1 (22C65)

### CumulusCI installation method

pip

### Error Gist

https://gist.github.com/Julian88Tex/85d9fd6869b9a419165914d2d903c9d4

### Additional information

I think the bigger issue here is that it would be helpful to have a demo repo with GitHub Actions showing how to setup 2GP feature branch testing since I suspect this may not actually be a bug but a lack of understanding on my end.

**Comment by Julian88Tex** [comment]
Never mind figured it out. I now see that this documentation seems to assume that you are using CCI reusable actions like `cumulus-actions/standard-workflows/.github/workflows/feature-2gp.yml` which is shown here: https://cumulusci.readthedocs.io/en/latest/github-actions.html#reusable-workflows

I ended up using one of them and added it to my current actions's unit test job as a dependency doing this:

```
jobs:
  build_feature_test_package:
    name: "Build Feature Test Package"
    runs-on: ubuntu-latest
    steps:
      - uses: cumulus-actions/build-feature-test-package@v1
        with:
            dev-hub-auth-url: "${{ secrets.SFDX_AUTH_URL_JULIAN }}"
            org-name: dev

  apex_unit_tests:
    name: 'Run Apex Unit Tests'
#     if: contains(github.event.pull_request.labels.*.name, 'ci') || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build_feature_test_package]
    steps:

[STEPS OMITTED FOR BREVEITY]
```
