### ISSUE TITLE
New Option `load_sfdx_project_paths` for dx_convert_from Task 

### ISSUE THREAD

**Issue by Szandor72** [SFDO-Tooling/CumulusCI#3543]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Does your feature request solve a current problem?

In DX projects, subfolders are common. At the same time, no source might exist in the DX default folder. This is important because the default DX command behaviour  

When setting up a CumulusCI project based on sub-foldered DX metadata, the current approach looks something [like this](https://github.com/SFDO-Community/declarative-lookup-rollup-summaries/blob/main/cumulusci.yml):

```
deploy_unmanaged:
    steps:
      0:
        task: dx_convert_from
        options:
          extra: "--sourcepath ./dlrs/libs/fflib-apexmocks,./dlrs/libs/fflib-common,./dlrs/libs/lrengine,./dlrs/libs/metadataservice,./dlrs/main"
```

This is because the underlying DX CLI Command will only convert metadata from the default folder. 

### Describe the solution you'd like

I suggest introducing a new option for the DX Convert Task: `load_sfdx_project_paths` (better name is welcomed)

If True, this option would scan the local sfdx project json file, identify all Package Directories and collect their path nodes and append them as `sourcepath` to the DX Convert Command

### Describe alternatives you've considered

The alternative is to manually write the info from the sfdx project json into cumulusci.yml as explained above

### Additional context

I'm happy to provide the necessary code if you provide me with a branch. I'd also need a bit of support writing an appropriate test that fakes (or mocks) a sfdx project json file.
