### ISSUE TITLE
`dx` task doesn't work for some commands like `project convert source`

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3593]
### Describe the bug

Recently, some `sfdx` being to error if they are passed parameters like they do not need like `-o` for `project convert source`. This conflicts with CumulusCI's model of always passing an org and results in an error.

### Reproduction steps

1. Create task:
```
    dx_test:
        description: Process and deploy the package metadata to the packaging org
        class_path: cumulusci.tasks.sfdx.SFDXOrgTask
        options:
            command: "project convert source"
```
2. Run `cci flow run dx_test --org dev`

Result: 
```
Error: Return code: 1
stderr: Error (1): Nonexistent flag: -u
See more help with --help
```
Expected Result: Source code is converted as expected.

### Your CumulusCI and Python versions

CumulusCI version: 3.75.1 (/Users/julianjoseph/.local/bin/cci)
Python version: 3.10.0 (/Users/julianjoseph/.local/pipx/venvs/cumulusci/bin/python)

### Operating System

MacOS 13.3.1

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/Julian88Tex/683337639be5acb7ed06fcfda43cefad

### Additional information

Seems like this even breaks `cci task run dx_convert_from --org dev` which means you cannot run task command as part of a flow.

Found a workaround by added a `#` to the end of the `--command` parameter: `command: "project convert source -r custom-metadata -d src-cmdt #"`. This comments out the org parameter added to the end by CCI.
