### ISSUE TITLE
Ability to Increment Major Versions when running `upload_production`

### ISSUE THREAD

**Issue by Julian88Tex** [SFDO-Tooling/CumulusCI#3605]
### Feature Type

I'm interested in extensions to existing CumulusCI functionality (e.g., broader applicability of an existing Task or Flow).

### Does your feature request solve a current problem?

Currently, it is not possible to increment a package Major Version with any CumulusCI tasks outside of using the `dx` or `command` tasks to create a custom command. For example, there is no way to go from version `33.2` of a package to `34.0` using CumulusCI OOTB tasks.

### Describe the solution you'd like

Add a task option for `upload_production` which allows incrementing of a package's Major Version.

### Describe alternatives you've considered

- Alternatively or in addition, it may make sense to also allow for the setting of a package version directly.

### Additional context

The best workaround I know of is to create a custom task that looks something like this (note this is for a 1GP package):

```
    upload_package_version:
        class_path: cumulusci.tasks.sfdx.SFDXOrgTask
        options:
            command: package1 version create --package-id 033XXXXXXXXX --name Release --managed-released
```

If you are using the `release_production` flow you'd probably want to update it with this task.

```
    release_production:
        steps:
            1:
                task: upload_package_version
```

When running this flow you'd need to add in a version:
```
cci flow run release_production -o upload_package_version__extra "-v 34.0"
```

Unfortunately, with this workaround you miss out on CumulusCI notifying you when a package install finishes so it becomes more difficult to trigger any follow-up tasks like automated installation and testing of the package.
