### ISSUE TITLE
Metadata permanent deleted from packaging with uninstall_packaged_incremental 

### ISSUE THREAD

**Issue by aniespica** [SFDO-Tooling/CumulusCI#3693]
### Describe the bug

We executed the command cci flow run `ci_master --org packaging`, and during step 6, which is `uninstall_packaged_incremental`, a significant number of fields from the package were deleted, and they cannot be undeleted. In the `cumulusci.yml` file, we had set `purge_on_delete` to `false`. However, we suspect that the CI process purged all the classes and fields, which is why we are unable to restore them. Can someone please explain how this task works?

```
tasks:
  uninstall_packaged_incremental:
    options:
      path: src
      package: Auctifera
      purge_on_delete: false
      ignore_types: ["ConnectedApp", "Report", "Dashboard"]
```

### Reproduction steps

1. Add new fields and classes to a Salesforce org.
2. Delete those classes and fields from the source controller.
3. Run the command `cci flow run ci_master --org packaging`.
4. The fields and classes are deleted and cannot be undeleted from the bin can

### Your CumulusCI and Python versions

CumulusCI version: 3.80.0 (/Users/anacabreraagudelo/.local/bin/cci)
Python version: 3.11.4 (/Users/anacabreraagudelo/.local/pipx/venvs/cumulusci/bin/python)

You have the latest version of CumulusCI ⛅

See the latest CumulusCI Release Notes: https://github.com/SFDO-Tooling/CumulusCI/releases/tag/v3.80.0

### Operating System

14.0 (23A344)

### Windows environment

PowerShell

### CumulusCI installation method

pipx
