### ISSUE TITLE
`update_admin_profile` task fails on namespaced org with Person Accounts enabled

### ISSUE THREAD

**Issue by noahisapilot** [SFDO-Tooling/CumulusCI#3762]
### Describe the bug

I am developing a namespaced, unlocked package with a dependency on a package that requires Person Accounts enabled. When using a namespaced org, the `update_admin_profile` task (which is used in important CCI flows such as `dev_org`) is failing. This does not occur if I use a non-namespaced org.

### Reproduction steps

1. Ensure the project has a namespace defined in `cumulusci.yml`:
```
project:
  name: MY-PROJECT
  package:
    name: MY-PROJECT
    api_version: "59.0"
    namespace: MY_NS
```
2. Add a `dev_namespaced` org to `cumulusci.yml`:
```
orgs:
  scratch:
    dev_namespaced:
      config_file: orgs/dev.json
      days: 7
      namespaced: true
```
3. Ensure the `orgs/dev.json` has Person Accounts enabled:
```
{
  "orgName": "MY-PROJECT - Dev Org",
  "edition": "Developer",
  "features": ["PersonAccounts"],
  "settings": {
  }
}
```
4. run `cci flow run dev_org --org dev_namespace`
5. Error:

> Error: Could not process MDAPI response: Update of Profile Admin: Error on line 644, col 29: In field: recordType - no RecordType named Account.Business_Account found

### Your CumulusCI and Python versions

umulusCI version: 3.84.3
Python version: 3.12.2

### Operating System

MacOS 14

### CumulusCI installation method

pipx

### Error Gist

https://gist.github.com/asbestossupply/1ae948bcce20b1e62ab4f1674824ff0e
