### ISSUE TITLE
Allow disabling default scratch org configs

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#710]
Currently, every project will always have the 4 default scratch org configurations.  We should support projects that want to disable one of the 4 default scratch org configs with the following yaml syntax in the project's cumulusci.yml file:

```
orgs:
    scratch:
        dev:
            config_file: None
```
