### ISSUE TITLE
Task Groupings

### ISSUE THREAD

**Issue by cdcarter** [SFDO-Tooling/CumulusCI#772]
from @davisagli:
> it'd be nice if we had a way to group tasks in the list, and then maybe a way to hide a group unless you have a flag in your personal settings. In other words I want a way to say "show me all the releng tasks" rather than needing to configure each one

**Comment by cdcarter** [comment]
Humble proposal:

a task definition looks like:
```
tasks:
    blah_task_name:
        class_path: blah
        description: blah
        options:
            name: option_is_blah
```
[JSON Schema definition for the tasks section of cumulusci.yml](https://gist.github.com/cdcarter/d3a10e03f12265f1f49af2aa3d9c8c40#file-schema-json-L102-L129)

I suggest we add a fourth, optional, key to the task definition object:

```
tasks:
    blah_task_name:
        group: releng
        class_path: blah
        description: blah
        options:
            name: option_is_blah
```
defined as a comma seperated list of strings .

If a task defines a group (or more than one), by default, it will *not* be returned by BaseTaskFlowConfig.list_tasks.

We'll also add a new property to the cumulusci section, which contains a comma severated list of groups:
```
cumulusci:
    keychain: MyKeyChainClass
    groups: releng, wlma
```

If a group is added to the cumulusci.groups key, then BaseTaskFlowConfig.list_tasks will now list tasks from that group. This can be overriden on the project yaml, or on an (e.g.) release engineers loal machine.

Still to figure out:
- are groups pre-registered besides just being referenced in a task?
- the behavior of defining a task with the same name as a globally hidden task in a project and not specifying group would be surprising. perhaps all tasks must have a group.
- at the CLI you should be able to list *all* tasks, and list all tasks for a specified list of groups. this is not the default. there's also a way to force running a task in a group, if its not your default group. oh, and see them.
- but unless you've specified a group in YAML or at runtime, the task is invisible.
- docs should list all tasks all groups.
