### ISSUE TITLE
UpdateDependencies should skip already processed dependencies

### ISSUE THREAD

**Issue by jlantz** [SFDO-Tooling/CumulusCI#831]
If you run UpdateDependencies with multiple Github dependencies, you can get duplication of dependencies via recursion.  For example:

```
project:
   dependencies:
       - github: 'https://github.com/SalesforceFoundation/Cumulus'
       - github: 'https://github.com/SFDO-Community/OutboundFundsNPSP'
```

In this case, OutboundFundsNPSP defines a dependency on the Cumulus repo in its cumulusci.yml.  UpdateDependencies should be smart enough to know it's already processed the Cumulus repository when it gets to the second reference to Cumulus from OutboundFundsNPSP and just skip that reference.
