### ISSUE TITLE
CCI Task Info doesn't show updated task list on modifying cumulusci.yml

### ISSUE THREAD

**Issue by mishraankit191** [SFDO-Tooling/CumulusCI#942]
If we use 

```
flows:
    dependencies:
        tasks:
            1:
                task: deploy_pre
            2:
                task: deploy_pre     
            3:
                task: update_dependencies    
```

cci flow info shows the updated steps

but if we use

```
flows:
    deploy_packaging:
        6:
            task: None
```

the flow info doesn't show that the step 6 task is marked to not run

We would like to see when any task/flow step is added/skipped/reordered on flow info consistently if possible
